
-- SET THE NETWORK PACKET SIZE
SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 1
GO
RECONFIGURE
GO
SP_CONFIGURE 'MAX DEGREE OF PARALLELISM',1
RECONFIGURE WITH OVERRIDE
GO
EXECUTE SP_CONFIGURE 'NETWORK PACKET SIZE', 8060
RECONFIGURE WITH OVERRIDE
GO
-- THE FOLLOWING VALUE HAS TO MATCH WITH THE LOCAL GIVEN. (It should be reserved 2GB for the OS)
-- 	PLEASE CALCULATE:
-- 	MAX SERVER MEMORY 
--		- 2GB (OS,QUEST,TIVOLI,etc.)
EXECUTE SP_CONFIGURE 'MAX SERVER MEMORY', 6144
RECONFIGURE WITH OVERRIDE
GO
EXECUTE SP_CONFIGURE 'FILL FACTOR', 95
RECONFIGURE WITH OVERRIDE
GO

-- CONTROL
EXECUTE SP_CONFIGURE

--SET THE  OPTION 'SHOW ADVANCED OPTIONS' TO THE DEFAULT VALUE 0: policy
EXECUTE SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 0
GO
RECONFIGURE
GO
